"use client";
import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import { TonConnectUIProvider } from "@tonconnect/ui-react";
import "./globals.css";
import "snes.css/dist/snes.min.css";

const PressStart2P = Press_Start_2P({ weight: "400", subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app"
// };

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={PressStart2P.className}>{children}</body>
		</html>
	);
}
